### ISSUE TITLE
Usage Example

### ISSUE THREAD

**Issue by 3wille** [weareinteractive/ansible-newrelic#10]
In the [usage section of the Readme](https://github.com/weareinteractive/ansible-newrelic#usage) you use the `newrelic_license_key` twice. The first one setting it to `yes` is overwritten so it should work but throws a warning nonetheless.

```
  vars:
    newrelic_license_key: yes
    newrelic_service_state: started
    newrelic_license_key: ab2fa361cd4d0d373833cad619d7bcc424d27c16
```
